[project]
name = "outlook-caldav-sync"
version = "0.1.0"
description = ""
authors = [{ name = "Max Mehl", email = "mail@mehl.mx" }]
readme = "README.md"
requires-python = ">=3.12 ,<4.0"
dependencies = ["icalendar (>=6.3.2,<7.0.0)", "caldav (>=2.2.3,<3.0.0)"]

scripts = { "outlook-caldav-sync" = "outlook_caldav_sync.main:main" }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
bump-my-version = "^1.2.4"
pylint = "^3.3.9"
isort = "^6.1.0"
black = "^25.9.0"
mypy = "^1.18.2"
types-pytz = "^2025.2.0.20250809"
types-requests = "^2.32.4.20250913"
types-icalendar = "^6.3.2.20251107"
pytest = "^8.4.2"

# FORMATTING settings
[tool.isort]
profile = "black"

[tool.black]
line-length = 100

# MYPY settings
[tool.mypy]
files = ["outlook_caldav_sync/*.py", "tests/*.py"]
disable_error_code = ["import-untyped"]

# Bump-My-Version
[tool.bumpversion]
commit = true
tag = true
allow_dirty = false
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
regex = true
search = "^version = \"{current_version}\""
replace = "version = \"{new_version}\""
